language: node_js
node_js:
- '12'
- '14'
deploy:
  provider: heroku
  api_key:
    secure: aDVfAthsp4sgspdMz43DYDWhJta4XKRIpCL/xII+JkQeAWP7GZcRu2KvcXTmlxCV9or2lBK7wUVT5aGQHvltVti9ozauqfbSSanI0YXznth9j2zMiWSBulp//Qdwg6+CBR927pzHITlUk268l1uvcKYwquK/tamx1xdgqueQMRN8U2/w2mTb0Z7ZEJr/bqMZlv98Znnzb709upqXag4zcTVXxJNPbAozp7rmQtMUApf9EbHQq2+X8UiAv8lWXz5NbLQDiWdJr/vu+T+I5Nup4T1LMbup6XTwdGgFwiWJMa93WBV4PhvjRotxa75rPqEz5YDLjR1hfTV505SkgwnHn20iz+/4LQF1ZMuW6sEvRsnNDtIfbFPsR/swSh0OCq1B6T0ahLjAWgkzvVesZ+URzJyWnrehmbZbW1NUdFNvy1YiR34v5sgW45SDpLSxtRHRFQcBk31YDZPKukvCyaDYdHbtqMGsufCCakcIhyK+L722tTKYgX0I/Ce7tIPdafvgtVPgfWQS3LIFkJgq7jFlxlLaAAgLtXJrRcJ2XCOhQrK2X4hGrzK9yb593uK2PNmBXU8yw0v+w74rcCYH14u08CUrcvwGexla8pMPZ69I8tR/jWxxjbDByh+BMEl6kL2LJktgTm1Cpaa6PUmLPNqjPnHgsrjlhL+4uMdfTJkLzE0=
  app: website-gautier
  on:
    repo: GautierP09/website
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
