language: node_js
node_js:
- '12'
- '14'
script:
- echo 'Starting'
- npm install
deploy:
  provider: heroku
  api_key:
    secure: kQU2E1fZUMhFzWtYx2cWaTnIi/TkEChjL9THen8vjxeapACv1rr0oKcFngHAyQic1laKCY73eL26A+MTfE1lnf6rObG2fo/PoNEjp0cs6R+TS55R8XQtZzLA+VL+wlQAyqqwW+OYkZmT4PVqEZDaV0lh3cmsdgot/eAQh9oqd68XrQX4G7VU26xj5mdbwQxUTACH5KwvvTOem/Qcww1azdiwzuX45D9VFjqX62TbTV6xXgFX7qZqJGJQywEAUxWL722/K5C10y5H8w2NyvLOZJUVUaIb22MzsbVQhahPeulnesxrS5egxH0tHtehRjzFRQKpxrx4bqdZB49z6Job+o4Oe2hFnRb8+zdAWpmXM6TJ6oD1otZXIJfOxKESADLu+S5Xf+Mn1JFA9Yr0wLTCs5Jk98bOXrPZfsJN8q3hZqJiFO61dnjZ6O5hJbFo8w5yq8hWlpYv+ZGl16JH7sq1mY0RwwxpV5/v/AIEBUXWY3tehL4O81FPbUvQ+DZdl7riS+wu4uNVbOGUVqYP2DsjROXCiyOKBsVknds1Vw0QywFmyeLvRj/m3zYt1LczHzvsYT81epio74S/3U3yfg3mZfCcQGsQYoF8H9fzjsqEcUz/746i3iOM9oE0fem+zDiFu4kgXHYKadlTIygX0HT7S3xSkDbQ5l7Kglm1mpj/1A4=
  app: gautier-website
  on:
    repo: GautierP09/website
    branch: main
  skip_cleanup: 'true'
