language: node_js
node_js:
- '14'
script:
- echo 'Starting'
- npm install
deploy:
  provider: heroku
  api_key:
    secure: WeeEiDT7vczFndIbvrnU3ChFLvP3htfSwW4YKlvOPmdEHzGcP+teY82mj1/A9tDY5LuGULmD3nR4+im4dWxsWte7tJ4EhvJWu36YPr9QX8x6ErgAC4mOGmY21C8woxRy+rITHhsH542/nfjK3l2w/4ObsXCqRrJZa2b1CUvM342u++QVg7OWJ5VjPaLyHlThH0aqmNtYYLdDZp2HWdUwfI0RCLxZLqaPMqAKE6NFiCSUWkSqYhWQQlLfssarq5gC0O1LpT2ywDZPf+N+EWCoFQnipOgxZdGinbnrxtZuHXQ51ySib94gd4LUr7OLQ/Fie3EXDknROE68KLagKzMbqbCxgZN5W7B1bA0/36bbFkUvRrGuOMVOkmLyygPNG+VbmXWKrmJ+ZrlRg34URjg47hq/fQlgFNj68nW7ARTRDpII961JWDNcTHkvjGKobyDcqdL+h/JR892jFlLSZtH5mAYO56rUDxFncskAi2OLfWibJPq8XDFgiE2OlpzL2vF9qLLWYMp6zGhu3xlwCSMcFCp/Vhj1p0LFLHSvJ4aD7/0on7i7nvUzpnG1dmWdzcKO62mc0Ra+jNnDNJlmLiSOcIubtFASskWk7qNh4NvrZhJEofIWZ5Ko0+hUakufza+iUfNOoUr8xN4WwIdcnOSt0+ss7QgVfSKDhHPPaloyLp0=
  app: gautier-website
  on:
    repo: GautierP09/website
    branch: main
  skip_cleanup: 'true'
