language: node_js
node_js:
- '12'
- '14'
script:
- echo 'Starting'
- npm install
deploy:
  provider: heroku
  api_key:
    secure: xDT0mlNQabzcUdrPrJ5zo2JZNv66VB8CL/Ih0hFkNW3RH60SVjj7MThMQnb8JqDpbNUHQ7rCBOsxfUYNt0x+70Qy4q+AkK+3cMMcW1kHOrY5qNFzG/KRxpGd4rDL9gwo9JnA/7hnm7nyvQHCF+Mv0WqhLSwjfImGMoyjOM2HsNuvpP+nZ979BPfbuYeGKIv0AQnAGd5KlN45qRBbq7fwBiIKXfAIlmA9AN0BuNkYHZ8Y7UGS7HFLdqozeEry/C+J+W9P0B/5UIvZRYELTdUfiIrK/2zOxNAdXV/+azUbetfgtpdgWJReui/nYcQ1caHE86a9Twhy5jRZzVYLZmJRFrV4/FO7K3TFJa/gz2u5CSPotEcuY0kt3juPAlhVGN0173J4JWhKRzv/LnvkYWhGT5m5aN3kd5lfvW9cALJZ5YgFdoJ1glOK+LMSVwgClcpvGg1mecpjzoAoKEyudqlmfUs6isTsyuEUroFUo3Uv14eNarPbMTuuf5F85ZGFVBDTRE4XtXLAVAwzWZ/XLfwo7mV6/CyPsqvE6sE5Zq58Bn1rmVBIkQUVr5FuwTaOQru6dZsiRaoQHLIlexaWPKsDZJPS3nbAd6DVkwDhC3dSQipACHyc/AKD/l+dfI/azu+w+yj90p33fpgM8A/9QAgxk/UyplKjk6O8pRULoWgH8Lc=
  app: website
  on:
    repo: GautierP09/website
    branch: main
  skip_cleanup: 'true'
